const express=require("express");const axios=require("axios");const app=express();app.use(express.json());const PORT=process.env.PORT||10000;
const PROXY_LIST=[process.env.PROXY_URL||"","https://thingproxy.freeboard.io/fetch/","https://api.codetabs.com/v1/proxy?quest=","https://corsproxy.io/?"].filter(Boolean);
const BASES=["https://www.sofascore.com/api/v1","https://api.sofascore.com/api/v1"];
const TELEGRAM_TOKEN=process.env.TELEGRAM_BOT_TOKEN||process.env.TELEGRAM_TOKEN||"";const CHAT_ID=process.env.TELEGRAM_CHAT_ID||process.env.CHAT_ID||"";
const POLL_MINUTES=Number(process.env.POLL_MINUTES||5);const SCORE_MIN=Number(process.env.SCORE_MIN||82);const SCORE_FORTE=Number(process.env.SCORE_FORTE||90);
const MAX_ALERTAS=Number(process.env.MAX_ALERTAS||3);const MAX_STATS=Number(process.env.MAX_STATS||4);const HORARIO_INICIO=Number(process.env.HORARIO_INICIO||9);const HORARIO_FIM=Number(process.env.HORARIO_FIM||23);
const historico=new Map(),enviados=new Map(),cacheStats=new Map(),cacheMomentum=new Map(),cacheIncidentes=new Map();let radarRodando=false,ultimoRadar=null,ultimoErro=null,ultimoProxy="nenhum";
const http=axios.create({timeout:20000,headers:{"User-Agent":"Mozilla/5.0","Accept":"application/json","Referer":"https://www.sofascore.com/","Origin":"https://www.sofascore.com"}});
async function sofaGet(path){
 for(const base of BASES){
  for(const proxy of PROXY_LIST){
   try{
    const url=`${base}${path}`;
    let finalUrl=url;
    if(proxy){
     if(proxy.includes("codetabs")||proxy.includes("allorigins")||proxy.includes("corsproxy")||proxy.includes("url=")||proxy.includes("quest=")){
      finalUrl=`${proxy}${encodeURIComponent(url)}`;
     }else{
      finalUrl=`${proxy}${url}`;
     }
    }
    const r=await http.get(finalUrl);
    if(r.data&&(r.data.events||r.data.statistics||r.data.graphPoints||r.data.incidents)){ultimoProxy=proxy||"direto";return r;}
   }catch(e){continue;}
  }
 }
 throw new Error("Todos proxys falharam");
}
function horaBrasil(){try{return parseInt(new Date().toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",hour12:false}),10);}catch{return new Date().getHours();}}
function isHorarioAtivo(){const h=horaBrasil();if(HORARIO_INICIO<=HORARIO_FIM)return h>=HORARIO_INICIO&&h<=HORARIO_FIM;return h>=HORARIO_INICIO||h<=HORARIO_FIM;}
function num(v){if(v==null)return 0;if(typeof v==="number")return isFinite(v)?v:0;const n=parseFloat(String(v).replace("%","").replace(",",".").trim());return isFinite(n)?n:0;}
function esperar(ms){return new Promise(r=>setTimeout(r,ms));}
async function enviarTelegram(t){if(!TELEGRAM_TOKEN||!CHAT_ID)return false;try{await axios.post(`https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage`,{chat_id:CHAT_ID,text:t,parse_mode:"Markdown",disable_web_page_preview:true},{timeout:10000});return true;}catch(e){return false;}}
function obterMinuto(j){const s=j.status?.type;if(s==="finished"||s==="canceled"||s==="postponed")return 0;const m=num(j.time?.minute);if(m>0)return Math.floor(m);const ini=j.time?.currentPeriodStartTimestamp||j.time?.period1StartTimestamp;if(ini){const agora=Math.floor(Date.now()/1000);const dif=agora-Number(ini);if(dif>=0&&dif<7200)return Math.floor(dif/60);}return 0;}
function extrairStats(data){const stats={shots:0,shotsOnTarget:0,corners:0,dangerousAttacks:0,attacks:0,possessionHome:0,possessionAway:0};const lista=data?.statistics||[];let grupos=[];const all=lista.find(x=>String(x.period).toUpperCase()==="ALL");if(all)grupos=all.groups||[];else grupos=lista.flatMap(x=>x.groups||[]);for(const g of grupos){for(const it of g.statisticsItems||[]){const nome=String(it.name||it.statisticsType||"").toLowerCase();const h=num(it.home),a=num(it.away);if(nome.includes("total shots"))stats.shots=h+a;if(nome.includes("shots on target")||nome.includes("shots on goal"))stats.shotsOnTarget=h+a;if(nome.includes("corner"))stats.corners=h+a;if(nome.includes("dangerous attack"))stats.dangerousAttacks=h+a;if(nome==="attacks"||nome.includes("total attacks"))stats.attacks=h+a;if(nome.includes("ball possession")||nome.includes("possession")){stats.possessionHome=h;stats.possessionAway=a;}}}return stats;}
async function buscarStats(id){const c=cacheStats.get(id);if(c&&Date.now()-c.timestamp<180000)return c.stats;try{const r=await sofaGet(`/event/${id}/statistics`);const s=extrairStats(r.data);cacheStats.set(id,{timestamp:Date.now(),stats:s});return s;}catch(e){return null;}}
async function buscarMomentum(id){const c=cacheMomentum.get(id);if(c&&Date.now()-c.timestamp<180000)return c.momentum;try{const r=await sofaGet(`/event/${id}/graph`);const pts=r.data?.graphPoints||[];if(!pts.length)return null;const ult=pts.slice(-10),ant=pts.slice(-20,-10);const medA=ult.length?ult.reduce((s,p)=>s+num(p.value),0)/ult.length:0;const medB=ant.length?ant.reduce((s,p)=>s+num(p.value),0)/ant.length:0;const dif=medA-medB;let tend="ESTÁVEL";if(dif>=8)tend="SUBINDO";else if(dif<=-8)tend="CAINDO";const m={diferenca:dif,tendencia:tend};cacheMomentum.set(id,{timestamp:Date.now(),momentum:m});return m;}catch(e){return null;}}
async function buscarIncidentes(id){const c=cacheIncidentes.get(id);if(c&&Date.now()-c.timestamp<180000)return c.incidentes;try{const r=await sofaGet(`/event/${id}/incidents`);const inc=r.data?.incidents||[];cacheIncidentes.set(id,{timestamp:Date.now(),incidentes:inc});return inc;}catch(e){return [];}}
function analisarEvolucao(id,stats,mom,min){const atual={minuto:min,shots:stats?.shots||0,shotsOnTarget:stats?.shotsOnTarget||0,corners:stats?.corners||0,dangerousAttacks:stats?.dangerousAttacks||0,timestamp:Date.now()};let ant=null;const lista=historico.get(id);if(lista&&lista.length)ant=lista[lista.length-1];const ev={shots:0,shotsOnTarget:0,corners:0,dangerousAttacks:0};if(ant){ev.shots=atual.shots-ant.shots;ev.shotsOnTarget=atual.shotsOnTarget-ant.shotsOnTarget;ev.corners=atual.corners-ant.corners;ev.dangerousAttacks=atual.dangerousAttacks-ant.dangerousAttacks;}if(!historico.has(id))historico.set(id,[]);const arr=historico.get(id);arr.push(atual);if(arr.length>6)arr.shift();return ev;}
function calcularScoreOver(jogo,stats,mom,ev){const min=obterMinuto(jogo);const gols=num(jogo.homeScore?.current)+num(jogo.awayScore?.current);let s=45;const m=[];if(min>=25&&min<=38){s+=10;m.push("janela 25-38'");}if(min>=70&&min<=84){s+=12;m.push("pressao 70-84'");}if(min>=85&&min<=90){s+=15;m.push("reta final");}if(stats){if(stats.shots>=8){s+=8;m.push(`${stats.shots} chutes`);}if(stats.shotsOnTarget>=4){s+=12;m.push(`${stats.shotsOnTarget} no alvo`);}if(stats.corners>=5){s+=8;m.push(`${stats.corners} esc`);}if(stats.dangerousAttacks>=35){s+=8;m.push(`${stats.dangerousAttacks} perigosos`);}}if(ev){if(ev.shots>=2){s+=7;m.push(`+${ev.shots} chutes`);}if(ev.shotsOnTarget>=1){s+=8;m.push(`+${ev.shotsOnTarget} no alvo`);}if(ev.corners>=1){s+=6;m.push(`+${ev.corners} esc`);}if(ev.dangerousAttacks>=8){s+=7;m.push(`+${ev.dangerousAttacks} perigosos`);}if(ev.shots>=2&&ev.shotsOnTarget>=1&&ev.dangerousAttacks>=8){s+=10;m.push("ACELERACAO");}}if(mom){if(mom.tendencia==="SUBINDO"){s+=10;m.push("subindo");}if(mom.tendencia==="CAINDO"){s-=8;m.push("caindo");}}if(gols>=4){s-=15;m.push("placar aberto");}if(gols<=2)s+=3;if(stats&&stats.shots<=3&&stats.shotsOnTarget<=1&&stats.corners<=2){s-=18;m.push("baixa prod");}s=Math.max(0,Math.min(100,Math.round(s)));return{score:s,motivos:m};}
function calcularScoreCorners(jogo,stats,mom,ev){const min=obterMinuto(jogo);if(!stats)return{score:0,motivos:[]};let s=42;const m=[];if(min>=65&&min<=84){s+=15;m.push(`janela ${min}'`);}if(min>=85&&min<=90){s+=20;m.push("reta final");}if(stats.corners>=5){s+=15;m.push(`${stats.corners} esc`);}if(stats.dangerousAttacks>=40){s+=10;m.push("perigosos altos");}if(ev&&ev.corners>=1){s+=10;m.push(`+${ev.corners} esc`);}if(mom&&mom.tendencia==="SUBINDO"){s+=10;m.push("subindo");}s=Math.max(0,Math.min(100,Math.round(s)));return{score:s,motivos:m};}
function chaveAlerta(id,mercado){return`${id}-${mercado}`;}function podeEnviar(id,mercado,score){const ch=chaveAlerta(id,mercado);const ant=enviados.get(ch);if(!ant)return true;if(score>=SCORE_FORTE&&ant.score<SCORE_FORTE)return true;if(Date.now()-ant.timestamp>1800000)return true;return false;}function marcarEnviado(id,mercado,score){enviados.set(chaveAlerta(id,mercado),{score,timestamp:Date.now()});}
function criarMensagem(jogo,mercado,analise,stats,mom,ev){const home=jogo.homeScore?.current??0,away=jogo.awayScore?.current??0,min=obterMinuto(jogo);const emoji=analise.score>=SCORE_FORTE?"🔥🔥🔥":"🟢";const nivel=analise.score>=SCORE_FORTE?"MUITO FORTE":"FORTE";let t=`${emoji} *ELITE RADAR V7.9.2 MULTI-PROXY*\n\n*${nivel} - ${analise.score}/100*\n\n⚽ *${jogo.homeTeam?.name||"Casa"}* ${home} x ${away} *${jogo.awayTeam?.name||"Fora"}*\n\n⏱️ ${min}'\n🏆 ${jogo.tournament?.name||"Comp"}\n\n🎯 *MERCADO:* ${mercado}\n\n📊 *MOTIVOS:*`;for(const mo of analise.motivos)t+=`\n• ${mo}`;if(stats)t+=`\n\n📈 LIVE\n• Chutes: ${stats.shots}\n• Alvo: ${stats.shotsOnTarget}\n• Esc: ${stats.corners}\n• Perig: ${stats.dangerousAttacks}`;if(mom)t+=`\n\n📈 MOM ${mom.tendencia}`;t+=`\n\n🔗 Proxy: ${ultimoProxy}\n🆔 ${jogo.id}`;return t;}
function limparMemoria(){const agora=Date.now();for(const[k,d]of enviados.entries())if(agora-d.timestamp>86400000)enviados.delete(k);for(const[id,lista]of historico.entries()){if(!lista.length){historico.delete(id);continue;}const ult=lista[lista.length-1];if(agora-ult.timestamp>7200000)historico.delete(id);}for(const[id,d]of cacheStats.entries())if(agora-d.timestamp>600000)cacheStats.delete(id);for(const[id,d]of cacheMomentum.entries())if(agora-d.timestamp>600000)cacheMomentum.delete(id);for(const[id,d]of cacheIncidentes.entries())if(agora-d.timestamp>600000)cacheIncidentes.delete(id);}
async function radar(){if(radarRodando)return{jogos:0,candidatos:0,sinais:0,ignorado:true};if(!isHorarioAtivo()){console.log(`[RADAR] Fora horario ${horaBrasil()}h`);return{jogos:0,candidatos:0,sinais:0,dormindo:true};}radarRodando=true;let jogos=0,candidatos=0,statsQ=0,sinais=0;try{const res=await sofaGet("/sport/football/events/live");const eventos=res.data?.events||[];jogos=eventos.length;console.log(`[V7.9.2] ${jogos} jogos via ${ultimoProxy}`);const lista=eventos.map(jogo=>{const min=obterMinuto(jogo);const gols=num(jogo.homeScore?.current)+num(jogo.awayScore?.current);let pri=0;if(min>=25&&min<=38)pri+=20;if(min>=70&&min<=90)pri+=30;if(gols<=2)pri+=10;if(gols>=4)pri-=15;return{jogo,minuto:min,prioridade:pri};}).filter(i=>{const m=i.minuto;const g=num(i.jogo.homeScore?.current)+num(i.jogo.awayScore?.current);if(m<25||m>90)return false;if(g>=5)return false;return(m>=25&&m<=38)||(m>=70&&m<=90);}).sort((a,b)=>b.prioridade-a.prioridade);candidatos=lista.length;for(const item of lista.slice(0,MAX_STATS)){if(sinais>=MAX_ALERTAS)break;const jogo=item.jogo;const stats=await buscarStats(jogo.id);statsQ++;await esperar(500);const mom=await buscarMomentum(jogo.id);await esperar(400);const inc=await buscarIncidentes(jogo.id);const vermelho=inc.some(x=>x.incidentType==="card"&&(x.incidentClass==="red"||x.incidentClass==="secondYellow"));const ev=analisarEvolucao(jogo.id,stats,mom,item.minuto);const over=calcularScoreOver(jogo,stats,mom,ev);if(vermelho){over.score=Math.min(100,over.score+3);over.motivos.push("vermelho");}if(over.score>=SCORE_MIN&&podeEnviar(jogo.id,"OVER",over.score)){const msg=criarMensagem(jogo,"OVER LIVE",over,stats,mom,ev);if(await enviarTelegram(msg)){marcarEnviado(jogo.id,"OVER",over.score);sinais++;}}if(sinais>=MAX_ALERTAS)break;const corn=calcularScoreCorners(jogo,stats,mom,ev);if(corn.score>=SCORE_MIN&&podeEnviar(jogo.id,"ESCANTEIOS",corn.score)){const msg=criarMensagem(jogo,"ESCANTEIOS LIVE",corn,stats,mom,ev);if(await enviarTelegram(msg)){marcarEnviado(jogo.id,"ESCANTEIOS",corn.score);sinais++;}}}limparMemoria();ultimoRadar=new Date().toISOString();ultimoErro=null;return{jogos,candidatos,statsQ,sinais,proxy:ultimoProxy,timestamp:ultimoRadar};}catch(e){ultimoErro=e.message;console.log("[RADAR ERRO]",e.message);return{jogos,candidatos,statsQ,sinais,erro:e.message,proxy:ultimoProxy};}finally{radarRodando=false;}}
app.get("/",(req,res)=>res.json({status:"online",sistema:"ELITE RADAR V7.9.2 MULTI-PROXY",horaBrasil:horaBrasil(),horarioAtivo:isHorarioAtivo(),proxys:PROXY_LIST,ultimoProxy,radarRodando,ultimoRadar,ultimoErro}));
app.get("/health",(req,res)=>res.json({versao:"V7.9.2 MULTI-PROXY",proxy:ultimoProxy,proxys:PROXY_LIST,radarRodando,ultimoRadar,ultimoErro}));
app.get("/radar",async(req,res)=>{const r=await radar();res.json(r);});
app.get("/telegram-test",async(req,res)=>{const ok=await enviarTelegram(`🟢 *V7.9.2 MULTI-PROXY*\n\nProxy atual: ${ultimoProxy}\nTeste OK`);res.json({enviado:ok,proxy:ultimoProxy});});
app.listen(PORT,()=>console.log(`V7.9.2 MULTI-PROXY porta ${PORT}`));
setInterval(()=>{radar().catch(e=>console.log(e.message));},Math.max(3,POLL_MINUTES)*60*1000);
setTimeout(()=>{radar().catch(e=>console.log(e.message));},5000);
